[project]
name = "backend"
version = "0.1.0"
description = "Backend server for the PeachTree Bank application for GreenStreet Interview"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "sqlalchemy>=2.0.42",
    "pydantic>=2.11.7",
]
